GET http://localhost:5097/api/customers

###
GET http://localhost:5097/api/customers/cbf82850-ffb8-4d59-8af8-7765e3baed82

###
POST http://localhost:5097/api/customers
Content-Type: application/json

{
    "githubusername": "tanya-dev",
    "name": "Katya",
    "customeraddressid": "570868df-9cb1-4600-ae1e-b10d3dafe8fc"
}

###
PUT http://localhost:5097/api/customers/b2936cc3-ab81-4ff2-9bb6-4bca79682543
Content-Type: application/json

{
    "githubusername": "mashadev",
    "name": "Maria",
    "customeraddressid": "570868df-9cb1-4600-ae1e-b10d3dafe8fc"
}

###
DELETE http://localhost:5097/api/customers/b2936cc3-ab81-4ff2-9bb6-4bca79682543


###
GET http://localhost:5097/api/customers/addresses